[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "a21fb78a1e9cb208cf307c78e43a09ae723558e7"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "811ad5f74eafda4ea6e4878723c5b347e6c2a6f94ddfb15afbb171eedaf82499"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.0/vegaliteassets-2.0.0-i686-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "bff8925a634282cbf9bd4ee1e4d0daee6f65ea01"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "5999ee5c222f3ded97ca35a70dc5876114fb19912b30aa65a17474be2d6daa6e"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.0/vegaliteassets-2.0.0-x86_64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "380738b242341a37e5d4408d08f89c6555674a6c"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "c0119be006c74c109a5453f899892555397cf7fb3f3df5984e26e7382526e0f0"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.0/vegaliteassets-2.0.0-aarch64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "dd364d401f2ad8b252eb54971751f91b9d83cf3e"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "4c01d14512bab72c8378709b7ed3df3ec28801ac437abe9271abba73ec763c6a"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.0/vegaliteassets-2.0.0-arm-linux-gnueabihf.tar.gz"
[[vegalite_app]]
arch = "powerpc64le"
git-tree-sha1 = "aacc6b438bc9a5eac4336fd19288efbaed56b3d9"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "4186eddb5dd9ab4d6d18d3ab1c56a1979b23258e8b50c435fba1cc3f4a4e6a0b"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.0/vegaliteassets-2.0.0-powerpc64le-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "6454370c4224dc673daf84a922974622e1ccacba"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "c2a340854bf9c4d75b73142305722e7a2ffb588e60f47c8872a3ff46fb2a2e61"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.0/vegaliteassets-2.0.0-i686-linux-musl.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "8aa48eccb101188f373500947cf6034c47c8059c"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "2dcacda2857663677658fee10c3fb39b80e75c82e831b636f04e55fe5bd529e4"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.0/vegaliteassets-2.0.0-x86_64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "41124d6f73243d7e9b49149b8b5783b531761dc7"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "9ef94d7efd7f5e30dbe8a920a7562c558ffa293660b5cf36c0ac328056909620"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.0/vegaliteassets-2.0.0-aarch64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "eb637fa085c5d6ef197620d5254462580bf8ff37"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "0769485f5af34f8af06aff8ebaff295561f50218b24b4790f15f3ca192131e54"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.0/vegaliteassets-2.0.0-arm-linux-musleabihf.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "957d74145a022f816c65dee6ff58b4817f6bc7d6"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "b11076d4e98b52f2e557fee09366eec2344efd10af1604d673d7deaf31f79246"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.0/vegaliteassets-2.0.0-x86_64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "c2e0ba071017ff50e2021cbc05596d675a820e35"
os = "freebsd"

    [[vegalite_app.download]]
    sha256 = "e797b0912be22a443c635942ae9bbe967f2eb00f2fd316ea32e8bd4112b30d65"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.0/vegaliteassets-2.0.0-x86_64-unknown-freebsd11.1.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "c89f3fd28b038d4e1c88fe4496e52a857b0a5f39"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "0ed0d11ab706d67eb7c39011bf75d8cc3a26440a76c2a61ff5109e572baa17ec"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.0/vegaliteassets-2.0.0-i686-w64-mingw32.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "3ace41a3932ffaf4167972af9db5f8f42b394cad"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "cb89ba8e13b9d907adfbb0581d1f004e2096859ae3da75b26ab92c0cb634fb35"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.0/vegaliteassets-2.0.0-x86_64-w64-mingw32.tar.gz"
