[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "d4dcabfb8c01168be9f732c96a9afa98fa935970"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "15526f7e5748716cf5e08f3d1b70a407f93ff77d2d7dddf5e41c4aff42e11430"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v1.0.0/vegaliteassets-1.0.0-i686-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "d92d25499fbd0e4b76aef7ed127f3c79f337990a"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "b4932b2dd78f4be9721a18d5eb4825f049898e80383f281d7255979cacb16c9e"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v1.0.0/vegaliteassets-1.0.0-x86_64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "ab1442a79ecb8a31ef730258b21020945d2e964f"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "f4286100394edfef91112ba971b8fb05cb8d056e7fe7aeb8c29e9d692d131e23"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v1.0.0/vegaliteassets-1.0.0-aarch64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "640c0cdc6d4d91ba7402dfb6db19952f811a1562"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "8fb7667fb8f54829b19f17ac3edf7639f19f72719dcfebfa209db6cec901d8b7"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v1.0.0/vegaliteassets-1.0.0-arm-linux-gnueabihf.tar.gz"
[[vegalite_app]]
arch = "powerpc64le"
git-tree-sha1 = "7a4779bf542e172b2987a453751fae28f2462e4a"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "39780f6f23f8d6d9efec9d3b4e499d4c916669ff18ed1ebfa6d5a88c91f00900"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v1.0.0/vegaliteassets-1.0.0-powerpc64le-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "fb7393b5c058dc3fe5d2a21f64d5153689e38a24"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "ba853fbfd2370a7f3fb917f1feb3ff9701c350a2cab6472d8ac38d294e2e3e48"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v1.0.0/vegaliteassets-1.0.0-i686-linux-musl.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "983566e6b279fc4482d5989ca479c749122ec7cd"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "e7ac8515299c287720d8ce165b35de36a15d9de357dda8b5cacf843215e0b235"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v1.0.0/vegaliteassets-1.0.0-x86_64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "7abe7c3b819e1920e9ab23e1d6a157a74477ad2c"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "198a273d93acab4efa2b1327b9b3bd061c078a14bbff00548b83da7de998d471"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v1.0.0/vegaliteassets-1.0.0-aarch64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "694863ee584fd6a25fe512b1591309435a5b3ada"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "f4e2abd18ac9f33473e01e160c2131c83960b7f9131227dfb5c25e9acb48e17d"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v1.0.0/vegaliteassets-1.0.0-arm-linux-musleabihf.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "57ee33928ba4598b1317d36e54fd0e4fe3dc332d"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "05cd010fd457587a994fc1f34b01e9b041d754b7b66197825ef4e5f13888b4b1"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v1.0.0/vegaliteassets-1.0.0-x86_64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "78c98547e94839a6411a5e6ffaa525c52dff6435"
os = "freebsd"

    [[vegalite_app.download]]
    sha256 = "5fc902b8015351b4e85786c89b12cecb3739f2ccab9be205d30cc942e272b79e"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v1.0.0/vegaliteassets-1.0.0-x86_64-unknown-freebsd11.1.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "231e5bf51ad86114a1aac690999daf4d00e8a04f"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "14242645e33172bdc96ea2518bba4d35010c63ad003060df03931cf9a088c0ac"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v1.0.0/vegaliteassets-1.0.0-i686-w64-mingw32.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "fab400553863c74cbf581bc03c63dfd0ac421825"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "a46b35a817e174153ac57d941899b1f25a405b5a84abbfdc2530b63d8e0eead3"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v1.0.0/vegaliteassets-1.0.0-x86_64-w64-mingw32.tar.gz"
