[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "7c0dd2191378003bfdb21dba276e26df63469a24"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "e499b5c2a495990f5ff4f824398245e91e3508d93d6ffaf982b424a614bd5a87"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.4/vegaliteassets-2.0.4-i686-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "eada60c928bb2012bc5ef6d6e8de2e66eda198be"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "8ae4043573b39b8789e510e919a7116cf84aaddcb1f2fa2d7db3a2342bb8be26"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.4/vegaliteassets-2.0.4-x86_64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "1d4dbf2aa4714d326a87017d16d867bb6e453ff5"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "03a0bf4b6e4b68376e8c43e6a40000cbd62db1f887e036d5bf140ecc902ad0f1"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.4/vegaliteassets-2.0.4-aarch64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "f969539f8906d1877c7c4f3077e74529455abcfd"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "577f76edf601bd7a20924d9d5fba865bb8124edc963fd4c863e4c3185a349f6c"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.4/vegaliteassets-2.0.4-arm-linux-gnueabihf.tar.gz"
[[vegalite_app]]
arch = "powerpc64le"
git-tree-sha1 = "9f5841902d61ed86b5a438305e0697a5a042d4ed"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "6335fc6982a155ce5c92f75c22ca7d5e0defa2d4f0c03f5988da0ae187b666de"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.4/vegaliteassets-2.0.4-powerpc64le-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "f95536e87944af4eeea204cde798839c15cbcf42"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "39c0bfc948008407731e8b5cc510b1500bb289352c03548a86e0a4b9d31ddc06"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.4/vegaliteassets-2.0.4-i686-linux-musl.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "aec7f0503516181694a5a7049dde8448dfca606e"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "38760af98700054dd13adde73eedc45d32a3b843dcb22b694b82a33f8e543f6f"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.4/vegaliteassets-2.0.4-x86_64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "6c0d192d926789494c707d361eb5c16761f4a786"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "4c31163cb7d04e448e3ae87a67f560fe84149c1232eee270abcbb4896b77e575"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.4/vegaliteassets-2.0.4-aarch64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "dc86bb52236c001d2c252551de701c67f258db0b"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "71eec272b2842ee90ab7b11e2cd33b68af78bfa1d977d67e1bbb018e443dae9d"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.4/vegaliteassets-2.0.4-arm-linux-musleabihf.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "5b30540cb38b55166fbe09931f2a5accfbe3396c"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "5ff0794b73dc116597382227878d6ed63cfb877236a77cbe6848e20a2785bc10"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.4/vegaliteassets-2.0.4-x86_64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "e7b59a79ba336f5d1f590bce5cb9bf5f1fd0ea76"
os = "freebsd"

    [[vegalite_app.download]]
    sha256 = "498a95a303ef42f0e76239caf0c196208d1a2e48dfe36cc83f736018d9a27989"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.4/vegaliteassets-2.0.4-x86_64-unknown-freebsd11.1.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "7b9322c337c759d2c65728ebdce7eb83d8b54678"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "598938319b9703af70f2b4cece00309c80a7b88410283fc9880ad8958c4f3e91"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.4/vegaliteassets-2.0.4-i686-w64-mingw32.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "1a3c649dbe58adebb3fcd75a47ddfe93df0a4916"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "50acbd387b0a26cd61821ec1a028bc79525c4e29bc9c2b00c5b3eb7c677b9bb3"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.4/vegaliteassets-2.0.4-x86_64-w64-mingw32.tar.gz"
