[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "d8d5f1ba1d8515096e5e85e11402c3344bca10fc"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "26f04f08a28f83fde92b19dc6e50163498f0209716fa170e648afd7be580263c"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.3.1/vegaliteassets-2.3.1-i686-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "a78b29cd51e4805c735ddec7d1fcce93ac7cf8fb"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "d41fc6898ac2858484f47add7ae780e8f2ab8ff54b4a64ed476b60b224567b2a"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.3.1/vegaliteassets-2.3.1-x86_64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "8a1facf1073d75b45e2e2de3c05d6250d5418879"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "c2c0ae10a7ea3af2007c9c5e557c7b352285d71b3d068c76fefb77cd7dece9eb"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.3.1/vegaliteassets-2.3.1-aarch64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "e5a38124991f1d0e7ffcfe576298e01ed4ae211d"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "ee99b1b90ded3937a8e6625436ac449b4e36a34679be10b03bfab1bd64df6dcb"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.3.1/vegaliteassets-2.3.1-arm-linux-gnueabihf.tar.gz"
[[vegalite_app]]
arch = "powerpc64le"
git-tree-sha1 = "e0daddfa30d96503be40d63014f4cd01510e8d80"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "d97e8e78f5303b3539783d81bd794aac8f00e9be8767378fd3de1afc3fa7810d"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.3.1/vegaliteassets-2.3.1-powerpc64le-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "bccd290ef6c3ecf3e506f3f40d1c7ae85f628fc0"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "856cd2d8b7465f82964f8bb30d80569bfff3b2ae1b9fadb1188279062df172fd"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.3.1/vegaliteassets-2.3.1-i686-linux-musl.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "6990f87e21bf6f2705afa7dad05e777dcb14ff4b"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "a5bce6d7ae8ab9a05490501752a9059b5678172235064f891792aeb125ac9062"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.3.1/vegaliteassets-2.3.1-x86_64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "19310946cb215068bb0335b77ba4da8a63a6c642"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "6cb8d577dcb125932ff1ad7664cfc4074ad4f0397bf0d515a5d629679cf2e1cf"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.3.1/vegaliteassets-2.3.1-aarch64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "67dcfd31be86bf44f3092d13147a9afc232f6078"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "03901fc6444e443d2bc17ce5675d57f846bdc5a6308758a753f365f1d90785e5"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.3.1/vegaliteassets-2.3.1-arm-linux-musleabihf.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "8fe2583a92c25c952e55463b6f7c6c345d00c83b"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "77997e716e474392a02695dc77826f33b8737921e6df80a1d61081ce6ce6e4aa"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.3.1/vegaliteassets-2.3.1-x86_64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "34308a921836f943a6732dc246d5d0d29327b51e"
os = "freebsd"

    [[vegalite_app.download]]
    sha256 = "176fd72daf6b6de63ca87dbde22cfe9a29ca6c7e32d5097daaa19b1892384e30"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.3.1/vegaliteassets-2.3.1-x86_64-unknown-freebsd11.1.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "81fc80c06e473b085b67d6547c93e5502cd1e9a7"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "58e6ea3c89e863de83e049a4f0ea2759ee8ae97f724bf65723aa46d398dfa61d"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.3.1/vegaliteassets-2.3.1-i686-w64-mingw32.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "afd8bd18b1995bc2e3b65732e0957d7ca08b6d1c"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "8705c11d5c137f913c8db25c744c3c004a5e3b46dc6e744d7178d222d0f02574"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.3.1/vegaliteassets-2.3.1-x86_64-w64-mingw32.tar.gz"
