[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "80dbb48a2bf3e344e8c25ea9b99e707e6ee1a103"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "56af10301fd23fd9f6e657f8a7c560029ecbfbfee1de6d085ebcc48dc658948d"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.1.1/vegaliteassets-2.1.1-i686-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "705eb8c5493e999f55641b8469b46ba151f079c3"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "92bedd6fa566e29aab1705f52a8691ab7ba060a59b9fb1102b773c28288dfd24"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.1.1/vegaliteassets-2.1.1-x86_64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "419bfd6e210bd940cd718c0fd80892b516b84455"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "b1bf6d65bdd441bde9a74602551324372dd509ee6b35ff66106ff49596470aaf"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.1.1/vegaliteassets-2.1.1-aarch64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "c1b9dd680307efd9990a99a9365684d323657f42"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "0c6d5f60d9a9cf80d2996b21df9d9432605ae5ab22d0ad968de5087f6a752503"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.1.1/vegaliteassets-2.1.1-arm-linux-gnueabihf.tar.gz"
[[vegalite_app]]
arch = "powerpc64le"
git-tree-sha1 = "8c44be9c7bb2c09add230ac187edfb8e98723852"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "540a1cc1e899064ea90de5be356d4661092cad8db84c9a7820d90e8fb72ff3c4"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.1.1/vegaliteassets-2.1.1-powerpc64le-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "4e9ec8fa7d1f144b0468e0feee69e8d36ae03cb1"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "a300282f848e500ffdf5473af65edc43a8b731b3cabb5f294ea2c34ec02c85c7"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.1.1/vegaliteassets-2.1.1-i686-linux-musl.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "e4b147c3e160f404acc2bbaec228407c09edda44"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "3eff09bd7b564f5cd4e125dc76827a65bbf754a78ffea50975619fcd92d86e75"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.1.1/vegaliteassets-2.1.1-x86_64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "38d88d59afb603b93bd8db43f783a67e9d05930b"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "86cb732bf2e10e349cee839115392ad513f68b21add10b6fe0a89623ce39ed4c"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.1.1/vegaliteassets-2.1.1-aarch64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "57a3e9cb9600e57ba18bbc1e1874ea10ffce0985"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "2e00255c2ab96b526f56c19c4004794ef0c06aa2c4badc24d12c078af459420e"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.1.1/vegaliteassets-2.1.1-arm-linux-musleabihf.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "128df618a641ee5236798ba2237963103bc601cc"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "41247a4c4866c9e0c5d66e6f986c560407220afbbe149f8bb45eb5daf942db95"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.1.1/vegaliteassets-2.1.1-x86_64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "643d28cc6e11e1b54120bba9af0aaaabe5200280"
os = "freebsd"

    [[vegalite_app.download]]
    sha256 = "38d0ae33e361d6ede1b18c0150cb03fb5c23fb4984ef86049b059c004150f181"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.1.1/vegaliteassets-2.1.1-x86_64-unknown-freebsd11.1.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "b764676f32de1de38aa0c3f4eaf58723ab7d4a71"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "6f27703f809b34522bf14fe6ce9ea6788ff6424bbe385e995fee5e22f44b6303"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.1.1/vegaliteassets-2.1.1-i686-w64-mingw32.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "023f70bb051927c7e517bdfcec4d5258d12422f0"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "8f6efce8d657e42cd5ee6ef1ae5888a6c10206198e9542a6f7d305590fe89325"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.1.1/vegaliteassets-2.1.1-x86_64-w64-mingw32.tar.gz"
