[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "c8587c78bc8eec664217ba300d141a8a531c57ef"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "2811e1b086c090446699411fc42dd6c6ca6a5bb03c63546d96684618cd0f6ba6"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.2.0/vegaliteassets-2.2.0-i686-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "6c62caedaf0ad0c51c499cf9d37ff85adee36d18"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "a9da53ad481c10c99657de606a2c016e68890d392bd103298a2a3b9d545c21ad"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.2.0/vegaliteassets-2.2.0-x86_64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "451bec01f423f8897ce7b088c1bdeeebe32759e3"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "43b589c240327d41a94c343c0f33e57dafed9ab386ae5d39414304bb80395cac"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.2.0/vegaliteassets-2.2.0-aarch64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "3e438958c65953cc586d47974c0b312f1de0b3c0"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "a5ba2e77467a4a085001f18d36d99b541797331287ee1fae8857836cf2527a9a"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.2.0/vegaliteassets-2.2.0-arm-linux-gnueabihf.tar.gz"
[[vegalite_app]]
arch = "powerpc64le"
git-tree-sha1 = "885c38ed115fd69dd8fde611b02931d2b0eb6196"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "ab305a93a10bd87f68f9c9fd773db73eb6fd3774e83a0487a60eb8ddfb542995"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.2.0/vegaliteassets-2.2.0-powerpc64le-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "c41c4b61d85be989d3cc82b17330b002a399ae59"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "f65c79cd445c563643d852207a7a5be672b584978b368d70e65d2d11cee05986"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.2.0/vegaliteassets-2.2.0-i686-linux-musl.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "6fc884f32d99250f626bf4394dee0305d9d71f90"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "cbfcb22b2cc8d2dde60ecdfaf5a6530abdb38c489fffb5ce933c3c4ddf91c73f"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.2.0/vegaliteassets-2.2.0-x86_64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "31c6e7f2861e53b6804e8283fe404000c3d9a962"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "dd77b9217fdbd544534d1a6b5e62f497520680ad3d114a4adf1744e99b945ddc"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.2.0/vegaliteassets-2.2.0-aarch64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "dba8ea6e6f97669744064126c11d584115dcc93d"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "101519e03df78094d9a860347e8df3072ebe92aefee7dffc9afdffc5e36e7f2e"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.2.0/vegaliteassets-2.2.0-arm-linux-musleabihf.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "322f54a8ea526a2ef7ae1877f23f6cfd3d271d67"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "490ebbb851e09f434d55bdc495ad2706ea801878ad5346a4d301e698726fb8c3"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.2.0/vegaliteassets-2.2.0-x86_64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "16499fcd639fab86ffeeeb655ad730da9b991c40"
os = "freebsd"

    [[vegalite_app.download]]
    sha256 = "27b6c73f74ce8a9d5de5017ef1c10818da00c9e8d9abfe37cf3e6ddc6029b701"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.2.0/vegaliteassets-2.2.0-x86_64-unknown-freebsd11.1.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "3ca46265bd5ab7c707655f1dfa22cb80bf648984"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "8d496f5781ed18d49c8a74ea4191ecdb3bef0edd8aca7b904eb74bffe17cf1a0"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.2.0/vegaliteassets-2.2.0-i686-w64-mingw32.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "011a45ea18db71cc2b8168c523a9ab6cc3a2fdcf"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "89ca5271ce2500569630fa542d23ad516bea3571c18fcf5e4b1394f1f1a4ae6b"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.2.0/vegaliteassets-2.2.0-x86_64-w64-mingw32.tar.gz"
