[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "a6f201328d872e814839f68230ed1c32dbd964da"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "60fa34ee77688692a46de4bb9ba76fd2fafb7f05a911140651f970d2ef7f2a16"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.5/vegaliteassets-2.0.5-i686-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "8e150e7c219ecfd8b18fb27ff830dc6b3628bf86"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "bd00c9f44967fa35467143c63018dd9f606ce34d8cd2cc4e728afaf22d533849"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.5/vegaliteassets-2.0.5-x86_64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "0d457206cf9e962b048daec7ee1cab07c0071d52"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "d5e06db81c310a8e9eac6bfb7dfa7f1f86ca4c549cdf030c5d8a010a7d30672e"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.5/vegaliteassets-2.0.5-aarch64-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "21c581cc025f8a1d2dcf1c9628986b936c1ba09a"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "d7d43f4b3f36242de20a5359c81d1c71d4155799455dcc48834a8a982859b9d2"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.5/vegaliteassets-2.0.5-arm-linux-gnueabihf.tar.gz"
[[vegalite_app]]
arch = "powerpc64le"
git-tree-sha1 = "4a9a188c16ed6698d0c3cec208fcc29b31a35333"
libc = "glibc"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "a104a975f55aaa7bdffc480ae889cbaaba4bd48017844618fdb85c1459774ebf"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.5/vegaliteassets-2.0.5-powerpc64le-linux-gnu.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "0c6f0c0dd844a0db3bb46cd087e475f6f9e3bfd0"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "bbc1bae7f7e8a200c63fa9fedb91bea3c82cd66f2c6c145e5def3b6012cfd0a1"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.5/vegaliteassets-2.0.5-i686-linux-musl.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "4c45ffacbae356847ab69cd2b210230f96d60928"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "6d6d60c373b15304f4db71a7f6beb9c646c3749f53a432b0dfedfb9acc7eb808"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.5/vegaliteassets-2.0.5-x86_64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "aarch64"
git-tree-sha1 = "d58ef9057c5df10f7f643aa0c6efe34e396f29d2"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "cedf0501013cc9d0cff3484ccc7272c6b30e574b1dbbc7c2fc978567c26c4280"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.5/vegaliteassets-2.0.5-aarch64-linux-musl.tar.gz"
[[vegalite_app]]
arch = "armv7l"
git-tree-sha1 = "678a8c540f161809e1bf8be9a98209f1356a41eb"
libc = "musl"
os = "linux"

    [[vegalite_app.download]]
    sha256 = "3049dd6b10f586f4ac0bb8609bfbe788a3eff77aad8db5a1595f45f3990f0180"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.5/vegaliteassets-2.0.5-arm-linux-musleabihf.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "d42b4bb4fae15e72bdb80f048f870e3e4bc65270"
os = "macos"

    [[vegalite_app.download]]
    sha256 = "851f9fb6af04715949d40c0d2668a184ccdd4424186ba0e6672e4ff1685c4397"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.5/vegaliteassets-2.0.5-x86_64-apple-darwin14.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "dd2f33adb1b50e4b6950ec38afe669f9ce86d25a"
os = "freebsd"

    [[vegalite_app.download]]
    sha256 = "e6bb717a27af790809f846ad22ba71b20bc7a37f81368045ead33a6fbb1cff1b"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.5/vegaliteassets-2.0.5-x86_64-unknown-freebsd11.1.tar.gz"
[[vegalite_app]]
arch = "i686"
git-tree-sha1 = "436f4dbefaf1bb62c4367e7180fc758380a64805"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "9e452be8d035abaa37a186d94b841e7abcf62c7e32b0740e13f4e144113f6fd7"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.5/vegaliteassets-2.0.5-i686-w64-mingw32.tar.gz"
[[vegalite_app]]
arch = "x86_64"
git-tree-sha1 = "49bb34f0d5cdbb584431bda9adb08b54d419d365"
os = "windows"

    [[vegalite_app.download]]
    sha256 = "17e78e3b3ceef57f2b283b810f006317ca76924a21d4ddd9d994aeb97074410f"
    url = "https://github.com/queryverse/VegaLiteBuilder/releases/download/v2.0.5/vegaliteassets-2.0.5-x86_64-w64-mingw32.tar.gz"
